### ISSUE TITLE
私密账号获取不到图片/视频

### ISSUE THREAD

**Issue by dzy49** [kaixinol/twitter_user_tweet_crawler#5]
私密账号只能读取到text 公开账号没有问题

**Comment by dzy49** [comment]
inject的script貌似不会给私密账号加下载按钮 加上下载的时候也没有用cookie 这两个都改一下就好了

**Comment by kaixinol** [comment]
已经引入 https://github.com/kaixinol/offline-twitter-cyber-fortune-teller-py/blob/4b5fc28518188745e6e6624db556addc441996e7/config/xpath.toml#L23-L26 的js代码以尝试修复（未测试）
